In [1]:
import numpy as np

In [2]:
my_array = np.arange(10000)

In [3]:
my_array

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [4]:
%time my_array = np.arange(10000)

CPU times: user 312 µs, sys: 58 µs, total: 370 µs
Wall time: 252 µs


In [27]:
data = np.random.randn(10,10)

In [28]:
data + data

array([[-0.5421227 , -1.24686944, -0.99040666, -0.26045754, -0.00873696,
        -3.01537351,  0.87671952, -2.02267176, -0.3039712 ,  4.87766911],
       [-3.55227379,  0.47301306,  0.42436838, -3.91674947, -1.59790368,
         1.70463439,  2.62357644,  1.79441828,  0.22172592, -1.15457827],
       [ 0.00801363,  2.82388757,  0.28903662,  2.77492241, -2.18460386,
         0.31318983,  0.135462  , -0.45279751,  1.67793135,  1.95065177],
       [ 0.43838597, -1.6406264 ,  0.72829296, -2.94677642,  0.88344147,
         0.30091738,  3.00388215,  3.52710743,  0.65850501, -2.17719057],
       [ 1.62350032,  2.47414517,  2.78008122, -0.34928576, -0.08535897,
         3.03466164,  1.88785711,  0.35968802,  0.87952451,  0.9169709 ],
       [ 1.75821491, -1.31290111,  2.70429722,  0.73319244,  2.67288451,
         3.09744249, -0.46869049,  2.1964353 ,  5.43127103,  2.35420958],
       [ 2.9528129 ,  0.10029336,  1.671886  , -4.00681037,  0.97088521,
        -0.63394573, -1.95461847,  0.65262171

In [21]:
data = np.random.randint(20,size = 2)

In [25]:
data * 10

array([160, 190])

In [29]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

In [30]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [31]:
arr1.dtype

dtype('float64')

In [32]:
arr2.dtype

dtype('int32')

In [35]:
arr1[1]

2.0

In [36]:
arr2[1]

2

In [39]:
arr2.fill(100)

In [40]:
arr2

array([100, 100, 100], dtype=int32)