In [10]:
import numpy as np

In [ ]:
bulb = [2,1,3,5,4]

In [ ]:
bulb

In [18]:
A = [2,1,3,5,4]

In [8]:
for i in range(len(A)):
    print(i, A[i],A[:i+1])

0 2 [2]
1 1 [2, 1]
2 3 [2, 1, 3]
3 5 [2, 1, 3, 5]
4 4 [2, 1, 3, 5, 4]


In [36]:
A

[2, 1, 3, 5, 4]

In [27]:
c = 1
t = 0
for i in range(len(A)):
    for j in range(i+1):
        print(A[j])
    c=c+1

2
2
1
2
1
3
2
1
3
5
2
1
3
5
4


In [7]:
index = [1,2,3,4,5]

In [8]:
index

[1, 2, 3, 4, 5]

In [11]:
np.cumsum(index)

array([ 1,  3,  6, 10, 15])

In [13]:
np.cumsum(A)

array([ 2,  3,  6, 11, 15])

In [14]:
np.cumsum(index) == np.cumsum(A)

array([False,  True,  True, False,  True])